{% set name = "epsie" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f90e5aeaaa670962331f3074ca52b79fed11681bf8b0d70c7f47dec2ec9ea92e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - numpy
    - python >=3.6
    - randomgen >=1.18
    - scipy >=0.16.0
    - six >1.10.0

test:
  imports:
    - epsie
    - epsie.chain
    - epsie.proposals
    - epsie.samplers

about:
  home: https://github.com/cdcapano/epsie
  license: GPL-3.0-or-later
  license_family: GPL
  # license currently missing from tarball: https://github.com/cdcapano/epsie/issues/14
  license_file: LICENSE
  summary: An Embarrassingly Parallel Sampler for Inference Estimation.

extra:
  recipe-maintainers:
    - duncanmmacleod
