{% set name = "epsie" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4dc2b7a26d5c0b09b5b8d76fd12a3fb414f6bad480a4cfa815160cba08f8a7d0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - numpy >=1.17.0
    - python >=3.6
    - randomgen >=1.18
    - scipy >=0.16.0
    - six >1.10.0

test:
  requires:
    - pip
  imports:
    - epsie
    - epsie.chain
    - epsie.proposals
    - epsie.samplers
  commands:
    - python -m pip check

about:
  home: https://github.com/cdcapano/epsie
  license: GPL-3.0-or-later
  license_family: GPL
  # license currently missing from tarball: https://github.com/cdcapano/epsie/issues/14
  license_file: LICENSE
  summary: An Embarrassingly Parallel Sampler for Inference Estimation.

extra:
  recipe-maintainers:
    - duncanmmacleod
